'\" t
.\"     Title: nvme-lnvm-write
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/26/2015
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "NVME\-LNVM\-WRITE" "1" "03/18/2015" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-write \- Write a single block to LightNvm namespace, returns applicable results\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme\-lnvm\-write\fR <device> [\-\-namespace\-id=<nsid> | \-n <nsid>]
                         [\-\-start\-block=<slba> | \-s <slba>]
                         [\-\-block\-count=<nlb> | \-c <nlb>]
                         [\-\-data\-size=<size> | \-z <size>]
                         [\-\-metadata\-size=<size> | \-y <size>]
                         [\-\-data=<data\-file> | \-d <data\-file>]
                         [\-\-prinfo=<prinfo> | \-p <prinfo>]
                         [\-\-limited\-retry | \-l]
                         [\-\-force\-unit\-access | \-f]
                         [\-\-latency | \-t]
.fi
.SH "DESCRIPTION"
.sp
The Write command writes the logical blocks specified by the command to the medium from the data data buffer provided\&. Will use stdin by default if you don\(cqt provide a file\&.
.SH "OPTIONS"
.PP
\-n <nsid>, \-\-namespace\-id=<nsid>
.RS 4
Write the data to the given nsid namespace\&.
.RE
.PP
\-s <slba>, \-\-start\-block=<slba>
.RS 4
Start logical block\&.
.RE
.PP
\-c <nlb>, \-\-block\-count=<nlb>
.RS 4
Logical block count\&.
.RE
.PP
\-z <size>, \-\-data\-size=<size>
.RS 4
Number of bytes data will be written to the medium\&. The size is no more than 4096\&.
.RE
.PP
\-y <size>, \-\-metadata\-size=<size>
.RS 4
Number of bytes meta\-data will be written to the medium\&.
.RE
.PP
\-d <data\-file>, \-\-data=<data\-file>
.RS 4
File to store data written to the mediun\&.
.RE
.PP
\-p <prinfo>, \-\-prinfo=<prinfo>
.RS 4
Protection information\&. This is optional\&.
.RE
.PP
\-l, \-\-limited\-retry
.RS 4
If set to
\fI1\fR, the controller should apply limited retry efforts\&. If cleaned to
\fI0\fR, the controller should apply all available error recovery means to write the data to the NVM\&. This is optional\&.
.RE
.PP
\-f, \-\-force\-unit\-access
.RS 4
If set to
\fI1\fR, data should be written to non\-volatile media before indicating command completion\&. This is optional\&.
.RE
.PP
\-\-latency, \-t
.RS 4
Print out the latency the IOCTL took (in us)\&.
.RE
.SH "EXAMPLES"
.sp
No examples yet\&.
.SH "NVME"
.sp
Part of the nvme\-user suite
