'\" t
.\"     Title: nvme-lnvm-read
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/18/2015
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "NVME\-LNVM\-READ" "1" "03/18/2015" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-read \- Read a single block from LightNvm namespace, returns applicable results\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme\-lnvm\-read\fR <device> [\-\-namespace\-id=<nsid> | \-n <nsid>]
                        [\-\-start\-block=<slba> | \-s <slba>]
                        [\-\-block\-count=<nlb> | \-c <nlb>]
                        [\-\-data\-size=<size> | \-z <size>]
                        [\-\-data=<data\-file> | \-d <data\-file>]
                        [\-\-prinfo=<prinfo> | \-p <prinfo>]
                        [\-\-limited\-retry | \-l]
                        [\-\-force\-unit\-access | \-f]
                        [\-\-latency | \-t]
.fi
.SH "DESCRIPTION"
.sp
The Read command reads the logical blocks specified by the command from the medium and copies to the data data buffer provided\&. Will use stdout by default if you don\(cqt provide a file\&.
.SH "OPTIONS"
.PP
\-n <nsid>, \-\-namespace\-id=<nsid>
.RS 4
Read the data from the given nsid namespace\&.
.RE
.PP
\-s <slba>, \-\-start\-block=<slba>
.RS 4
Start logical block\&.
.RE
.PP
\-c <nlb>, \-\-block\-count=<nlb>
.RS 4
Logical block count\&.
.RE
.PP
\-z <size>, \-\-data\-size=<size>
.RS 4
Number of bytes data will be read from the medium\&. The size is no more than 4096\&.
.RE
.PP
\-d <data\-file>, \-\-data=<data\-file>
.RS 4
File to store data read from the mediun\&.
.RE
.PP
\-p <prinfo>, \-\-prinfo=<prinfo>
.RS 4
Protection information\&. This is optional\&.
.RE
.PP
\-l, \-\-limited\-retry
.RS 4
If set to
\fI1\fR, the controller should apply limited retry efforts\&. If cleaned to
\fI0\fR, the controller should apply all available error recovery means to return the data to the host\&. This is optional\&.
.RE
.PP
\-f, \-\-force\-unit\-access
.RS 4
If set to
\fI1\fR, data should be returned from non\-volatile media\&. This is optional\&.
.RE
.PP
\-\-latency, \-t
.RS 4
Print out the latency the IOCTL took (in us)\&.
.RE
.SH "EXAMPLES"
.sp
No examples yet\&.
.SH "NVME"
.sp
Part of the nvme\-user suite
